<a href="https://colab.research.google.com/github/ShotaroSessions/Machine-Learning/blob/master/pytorch_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from __future__ import print_function
import torch

The initial values of a tensor will be whatever values were in the allocated memory at the time of declaration. Creates a 5 by 3 matrix:

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[4.5983e-36, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])


Randomly initialized matrix:

In [3]:
x = torch.rand(5,3)
print(x)

tensor([[0.5195, 0.0145, 0.3172],
        [0.2620, 0.0601, 0.2663],
        [0.2359, 0.2960, 0.2440],
        [0.2423, 0.9096, 0.2418],
        [0.1227, 0.4096, 0.7688]])


Matrix of zeros of dtype long:

In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


Directly from data:

In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


From an existing Tensor:

In [6]:
x = x.new_ones(5, 3, dtype=torch.double)
print(x)

x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[-0.8386,  0.1416, -2.0018],
        [-0.7200, -0.9223, -0.8010],
        [-1.3291,  1.8973,  0.5242],
        [-1.3161, -0.4696, -1.7896],
        [ 0.5718, -1.2506,  0.3185]])


Get size:

In [7]:
print(x.size())

torch.Size([5, 3])


Addition: torch

In [8]:
y = torch.rand(5, 3)
print(torch.add(x, y))

tensor([[-0.4780,  0.9001, -1.5283],
        [ 0.1831, -0.5248, -0.4339],
        [-1.1220,  2.2831,  1.3851],
        [-0.9937,  0.5042, -0.7977],
        [ 0.6612, -0.3228,  1.2771]])


Addition: output to tensor

In [9]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[-0.4780,  0.9001, -1.5283],
        [ 0.1831, -0.5248, -0.4339],
        [-1.1220,  2.2831,  1.3851],
        [-0.9937,  0.5042, -0.7977],
        [ 0.6612, -0.3228,  1.2771]])


Addition: in place

In [10]:
y.add(x)
print(x)

tensor([[-0.8386,  0.1416, -2.0018],
        [-0.7200, -0.9223, -0.8010],
        [-1.3291,  1.8973,  0.5242],
        [-1.3161, -0.4696, -1.7896],
        [ 0.5718, -1.2506,  0.3185]])


Resizing tensors:

In [11]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


NumPy Array to Torch Tensor:

In [12]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors

Tensors can be moved using the .to method:

In [13]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
